"""empty message

Revision ID: 84cd86350dbe
Revises: a9e43112c8ce
Create Date: 2022-09-21 17:09:21.260851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cd86350dbe'
down_revision = 'a9e43112c8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('title', sa.String(length=120), nullable=False))
    op.drop_column('favorite', 'titulo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('titulo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('favorite', 'title')
    # ### end Alembic commands ###
