"""empty message

Revision ID: 9b580bf79067
Revises: 3820b091675e
Create Date: 2022-09-21 14:26:02.815762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b580bf79067'
down_revision = '3820b091675e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('url', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'url')
    # ### end Alembic commands ###
