"""empty message

Revision ID: a9e43112c8ce
Revises: 9b580bf79067
Create Date: 2022-09-21 17:05:32.839217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e43112c8ce'
down_revision = '9b580bf79067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('url_image', sa.String(length=120), nullable=False))
    op.add_column('favorite', sa.Column('titulo', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'titulo')
    op.drop_column('favorite', 'url_image')
    # ### end Alembic commands ###
